In [1]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
from sklearn.datasets import load_boston
boston = load_boston()
boston.keys()

dict_keys(['data', 'target', 'DESCR', 'feature_names'])

In [4]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(boston.data, boston.target)

In [8]:
np.set_printoptions(suppress=True)

In [9]:
print(X_train)

[[   0.17142    0.         6.91    ...,   17.9      396.9       10.21   ]
 [   0.77299    0.         8.14    ...,   21.       387.94      12.8    ]
 [   0.03738    0.         5.19    ...,   20.2      389.4        6.75   ]
 ..., 
 [   0.0578     0.         2.46    ...,   17.8      396.9        5.04   ]
 [   0.06162    0.         4.39    ...,   18.8      364.61      12.67   ]
 [   0.10659   80.         1.91    ...,   22.       376.04       5.57   ]]


In [11]:
X_train.mean(axis=0)

array([   3.44449485,   11.62664908,   10.97422164,    0.07915567,
          0.55173245,    6.27398153,   67.40580475,    3.82088364,
          9.53034301,  407.33773087,   18.46833773,  355.93583113,
         12.55277045])

In [12]:
X_train.std(axis=0)

array([   8.16975917,   23.54075906,    6.75966074,    0.26998158,
          0.11520785,    0.69633172,   28.51264624,    2.0845705 ,
          8.71271189,  167.98728412,    2.14260713,   90.88943013,
          7.08940858])

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [14]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [15]:
X_scaled = scaler.transform(X_train)

In [16]:
X_scaled.shape

(379, 13)

In [20]:
X_scaled.mean(axis=0)

array([ 0., -0.,  0., -0., -0., -0.,  0.,  0.,  0., -0.,  0.,  0., -0.])

In [21]:
X_scaled.std(axis=0)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])